# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-ce41c749-af9f-430e-8b52-a04d76b0b41c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ce41c749-af9f-430e-8b52-a04d76b0b41c".device =
    "/dev/disk/by-uuid/ce41c749-af9f-430e-8b52-a04d76b0b41c";
  boot.initrd.luks.devices."luks-ce41c749-af9f-430e-8b52-a04d76b0b41c".crypttabExtraOpts = [
    "tries=10"
  ];

  # The installer declared this encrypted swap device in configuration.nix,
  # separately from its generated hardware file. The flake needs it as well.
  boot.initrd.luks.devices."luks-beb7d44b-251f-4e68-914d-1743e9f48580" = {
    device = "/dev/disk/by-uuid/beb7d44b-251f-4e68-914d-1743e9f48580";
    crypttabExtraOpts = [ "tries=10" ];
  };
  boot.resumeDevice = "/dev/mapper/luks-beb7d44b-251f-4e68-914d-1743e9f48580";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4C4A-872A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-beb7d44b-251f-4e68-914d-1743e9f48580"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
