[profiles.default]
config_file = "./profiles/atlas.go.tmpl"
config_file_type = "template"

[[profiles.default.conditions.required_monitors]]
description = "Philips Consumer Electronics Company PHL 246E9Q 0x000036F7"

[[profiles.default.conditions.required_monitors]]
description = "Shenzhen KTC Technology Group PMO G241-FFK"

[fallback_profile]
config_file = "./profiles/fallback.conf"
config_file_type = "static"
